# Generated by Django 6.0.6 on 2026-06-24 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('age_category', models.CharField(choices=[('X10', 'X10'), ('X12', 'X12'), ('X14', 'X14'), ('X16', 'X16'), ('VSE', 'VSE'), ('M16', 'M16'), ('M18', 'M18'), ('MSE', 'MSE')], max_length=10)),
                ('requires_24_second_operator', models.BooleanField(default=False, help_text='Whether this team requires a 24-second operator for their games.')),
            ],
            options={
                'ordering': ['age_category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('away_team', models.CharField(max_length=100)),
                ('game_type', models.CharField(choices=[('HOME', 'Home'), ('AWAY', 'Away')], default='HOME', max_length=10)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('court', models.CharField(choices=[('1', 'Court 1'), ('2', 'Court 2')], max_length=1)),
                ('required_referees', models.PositiveIntegerField(default=2, help_text="Number of referees needed for this game's age category.")),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='core.season')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='core.team')),
            ],
            options={
                'ordering': ['date', 'time', 'court'],
                'unique_together': {('date', 'time', 'court')},
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('REFEREE', 'Referee'), ('SCORER', 'Scorer'), ('TIMER', 'Timer'), ('24_SECOND_OPERATOR', '24 Second Operator')], max_length=20)),
                ('slot_number', models.PositiveIntegerField(default=1, help_text='Slot number for tasks that need multiple people (e.g., Referee 1, Referee 2).')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.game')),
            ],
            options={
                'ordering': ['task_type', 'slot_number', 'game'],
                'unique_together': {('game', 'task_type', 'slot_number')},
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('is_coach', models.BooleanField(default=False)),
                ('referee_certification', models.CharField(choices=[('NONE', 'None'), ('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3'), ('T4', 'T4'), ('T5', 'T5'), ('T6', 'T6')], default='NONE', max_length=10)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='core.team')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.player')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.task')),
            ],
            options={
                'unique_together': {('task', 'player')},
            },
        ),
    ]
