# Generated by Django 6.0.6 on 2026-06-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_team_age_category_alter_game_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='referee_certification',
            field=models.CharField(choices=[('NONE', 'None'), ('F', 'F-diploma'), ('SENIOR', 'Senior')], default='NONE', max_length=10),
        ),
    ]
