# Generated by Django 6.0.6 on 2026-07-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_player_referee_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='coached_teams',
            field=models.ManyToManyField(blank=True, help_text='Teams this player coaches (in addition to their own team).', related_name='coaches', to='core.team'),
        ),
    ]
