# Generated by Django 6.0.6 on 2026-07-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_game_options_game_half'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='referee_certification',
            field=models.CharField(choices=[('NONE', 'None'), ('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3'), ('T4', 'T4'), ('T5', 'T5'), ('T6', 'T6'), ('F', 'F-diploma'), ('SENIOR', 'Senior')], default='NONE', max_length=10),
        ),
    ]
