# Generated by Django 6.0.6 on 2026-07-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_emailverificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='optional_referees',
            field=models.PositiveIntegerField(default=0, help_text='Additional referee slots that are optional.'),
        ),
        migrations.AddField(
            model_name='team',
            name='require_scorer',
            field=models.BooleanField(default=True, help_text='Whether a scorer slot is required.'),
        ),
        migrations.AddField(
            model_name='team',
            name='require_timer',
            field=models.BooleanField(default=True, help_text='Whether a timer slot is required.'),
        ),
        migrations.AddField(
            model_name='team',
            name='required_referees',
            field=models.PositiveIntegerField(default=2, help_text='Number of referee slots that must be filled.'),
        ),
        migrations.AddField(
            model_name='team',
            name='requires_24_second_operator',
            field=models.BooleanField(default=False, help_text='Whether a 24-second operator slot is required.'),
        ),
    ]
