# Generated by Django 6.0.6 on 2026-07-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_team_optional_referees_team_require_scorer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgeCategorySettings',
        ),
        migrations.AddField(
            model_name='team',
            name='parent_responsible',
            field=models.BooleanField(default=False, help_text='Whether parents (not players) are responsible for tasks on this team.'),
        ),
    ]
