# Generated by Django 6.0.6 on 2026-06-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='age_category',
            field=models.CharField(choices=[('X10', 'X10'), ('X12', 'X12'), ('X14', 'X14'), ('X16', 'X16'), ('VSE', 'VSE'), ('M16', 'M16'), ('M18', 'M18'), ('M22', 'M22'), ('MSE', 'MSE')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='game',
            unique_together={('season', 'date', 'time', 'court')},
        ),
    ]
