# Generated by Django 6.0.6 on 2026-07-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_player_coached_teams'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['half', 'date', 'time', 'court']},
        ),
        migrations.AddField(
            model_name='game',
            name='half',
            field=models.CharField(choices=[('1', 'First Half'), ('2', 'Second Half')], default='1', help_text='Which half of the season this game belongs to.', max_length=1),
        ),
    ]
