# Generated by Django 6.0.6 on 2026-07-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_player_referee_certification'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeCategorySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_category', models.CharField(choices=[('X10', 'X10'), ('X12', 'X12'), ('X14', 'X14'), ('X16', 'X16'), ('VSE', 'VSE'), ('M16', 'M16'), ('M18', 'M18'), ('M22', 'M22'), ('MSE', 'MSE')], max_length=10, unique=True)),
                ('required_referees', models.PositiveIntegerField(default=2, help_text='Number of referee slots to create for games in this category.')),
                ('scorer', models.BooleanField(default=True, help_text='Whether a scorer slot is required for this category.')),
                ('timer', models.BooleanField(default=True, help_text='Whether a timer slot is required for this category.')),
                ('requires_24_second_operator', models.BooleanField(default=False, help_text='Whether a 24-second operator slot is required for this category.')),
            ],
            options={
                'verbose_name_plural': 'age category settings',
                'ordering': ['age_category'],
            },
        ),
        migrations.RemoveField(
            model_name='game',
            name='required_referees',
        ),
        migrations.RemoveField(
            model_name='team',
            name='requires_24_second_operator',
        ),
    ]
