# Generated by Django 6.0.6 on 2026-07-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_agecategorysettings_remove_game_required_referees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agecategorysettings',
            name='optional_referees',
            field=models.PositiveIntegerField(default=0, help_text='Number of additional referee slots that may be filled but are not required (e.g. a 2nd referee for X10/X14 games).'),
        ),
        migrations.AddField(
            model_name='task',
            name='optional',
            field=models.BooleanField(default=False, help_text='Whether this slot is optional (e.g. a 2nd referee that is not required to be filled).'),
        ),
        migrations.AlterField(
            model_name='agecategorysettings',
            name='required_referees',
            field=models.PositiveIntegerField(default=2, help_text='Number of referee slots that must be filled for this category.'),
        ),
    ]
