# Generated by Django 6.0.6 on 2026-08-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_delete_agecategorysettings_team_parent_responsible'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='location',
            field=models.CharField(default='Den Ekkerman', help_text='Venue where the game is played.', max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='parent_responsible',
            field=models.BooleanField(default=False, help_text='Whether parents (not players) are responsible for scorer and timer tasks on this team.'),
        ),
    ]
