# Generated by Django 6.0.6 on 2026-08-16 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_game_team_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='own_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_games', to='core.team'),
        ),
    ]
