# Generated by Django 6.0.6 on 2026-09-14 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_siteconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, default='', help_text='Optional free-text note recording why this version was sent.', max_length=500)),
                ('content_hash', models.CharField(help_text='SHA-256 over the normalized payload, used for dedupe.', max_length=64)),
                ('payload', models.JSONField(help_text='Canonical games/tasks/assignments for the whole season.')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.season')),
            ],
            options={
                'ordering': ['season', 'number'],
                'unique_together': {('season', 'number')},
            },
        ),
    ]
