# Generated by Django 6.0.6 on 2026-09-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_scheduleversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleversion',
            name='artifact',
            field=models.BinaryField(blank=True, help_text='Exact PDF/CSV bytes generated at capture time.', null=True),
        ),
        migrations.AddField(
            model_name='scheduleversion',
            name='artifact_format',
            field=models.CharField(blank=True, choices=[('pdf', 'PDF'), ('csv', 'CSV')], default='', help_text='Format of the stored artifact.', max_length=8),
        ),
    ]
